/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CodigoEspejo;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.OK_OPTION;

/**
 *
 * @author Ricardo
 */
public class CodigoEspejo extends javax.swing.JFrame {

   
    
    /**
     * Creates new form Aplicacion1
     */
    public CodigoEspejo() {
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejecutar = new javax.swing.JButton();
        datos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ejecutar)
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        // TODO add your handling code here:
        int j = 0;
        String Resultado = "";
        for(j=0; j < datos.getText().length();j++)
        {
            char caracter = datos.getText().charAt(j);
            switch (caracter)
            {case 'A':
                Resultado = Resultado + "Z";
                break;
            case 'B':
                Resultado = Resultado + "Y";
                break;
            case 'C':
                Resultado = Resultado + "X";
                break;
            case 'D':
                Resultado = Resultado +"W";
                break;
            case 'E':
                Resultado = Resultado +"V";
                break;
            case 'F':
                Resultado = Resultado +"U";
                break;
            case 'G':
                Resultado = Resultado +"T";
                break;
            case 'H':
                Resultado = Resultado + "S";
                break;
            case 'I':
                Resultado = Resultado + "R";
                break;
            case 'J':
                Resultado = Resultado + "Q";
                break;    
            case 'K':
                Resultado = Resultado + "P";
                break;
            case 'L':
                Resultado = Resultado + "O";
                break;
            case 'M':
                Resultado = Resultado + "N";
                break;
            case 'N':
                Resultado = Resultado + "M";
                break;
            case 'O':
                Resultado = Resultado + "L";
                break;
            case 'P':
                Resultado = Resultado +"K";
                break;
            case 'Q':
                Resultado = Resultado + "J";
                break;
            case 'R':
                Resultado = Resultado + "I";
                break;
            case 'S':
                Resultado = Resultado + "H";
                break;
            case 'T':
                Resultado = Resultado + "G";
                break;
            case 'U':
                Resultado = Resultado + "F";
                break;
            case 'V':
                Resultado = Resultado + "E";
                break;
            case 'W':
                Resultado = Resultado +"D";
                break;
            case 'X':
                Resultado = Resultado + "C";
                break;
            case 'Y':
                Resultado = Resultado + "B";
                break;
            case 'Z':
                Resultado = Resultado + "A";
                break;
            case ' ':
                Resultado = Resultado + " ";
                break;    
            default:
                break;
            }
        }
        
     JOptionPane.showConfirmDialog(null,Resultado,"Resultado",OK_CANCEL_OPTION,INFORMATION_MESSAGE);
     
    }//GEN-LAST:event_ejecutarActionPerformed

    private void datosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datosKeyReleased
        // TODO add your handling code here:
         datos.setText(datos.getText().toUpperCase());
             
    }//GEN-LAST:event_datosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodigoEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodigoEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodigoEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodigoEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodigoEspejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datos;
    private javax.swing.JButton ejecutar;
    // End of variables declaration//GEN-END:variables
}
